In [74]:
import pandas as pd 
import numpy as np 

In [75]:
df = pd.read_csv('diabetes.csv')

In [76]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [77]:
df.shape

(768, 9)

In [78]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [81]:
X= df.drop('Outcome',axis = 1)
y= df['Outcome']

In [82]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y ,random_state=0,test_size=0.2)

In [83]:
from sklearn.linear_model import  LogisticRegression

In [84]:
log = LogisticRegression()

In [85]:
log.fit(X_train,y_train)

C:\Users\Rrs computers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [86]:
y_pred_train  = log.predict(X_train)

In [87]:
y_pred_train

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [88]:
count = 0
for t,p in zip(y_train,y_pred_train):
    if t==p:
        count+=1
count


474

In [89]:
len(X_train)

614

In [90]:
count/len(X_train)

0.7719869706840391

In [91]:
from sklearn.metrics import accuracy_score


In [92]:
accuracy_score(y_train,y_pred_train)

0.7719869706840391

In [93]:
from sklearn.metrics import classification_report

In [94]:

cr  = classification_report(y_train,y_pred_train)

In [95]:
print(cr)

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       393
           1       0.73      0.58      0.65       221

    accuracy                           0.77       614
   macro avg       0.76      0.73      0.74       614
weighted avg       0.77      0.77      0.77       614



In [96]:
from sklearn.metrics import confusion_matrix

In [97]:
confusion_matrix(y_train,y_pred_train)

array([[345,  48],
       [ 92, 129]])

In [98]:
y_pred_test = log.predict(X_test)

In [99]:

print(confusion_matrix(y_test,y_pred_test))

[[98  9]
 [18 29]]


In [100]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



In [101]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [102]:
class_0 = df[df.Outcome == 0].sample(268)

In [103]:
class_1 =  df[df.Outcome == 1].sample(268)

In [104]:
new_data = pd.concat([class_0,class_1]).sample(536)

In [105]:
new_data.Outcome.value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [106]:
X = new_data.drop('Outcome',axis=1)
y = new_data.Outcome

In [107]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [108]:
log.fit(X_train,y_train)

C:\Users\Rrs computers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [109]:
y_predic_train = log.predict(X_train)

In [110]:
accuracy_score(y_train,y_predic_train)

0.7593457943925234

In [111]:
print(classification_report(y_train,y_predic_train))

              precision    recall  f1-score   support

           0       0.75      0.79      0.77       215
           1       0.77      0.73      0.75       213

    accuracy                           0.76       428
   macro avg       0.76      0.76      0.76       428
weighted avg       0.76      0.76      0.76       428



In [112]:
confusion_matrix(y_train,y_predic_train)

array([[169,  46],
       [ 57, 156]])

In [113]:
y_predic_test = log.predict(X_test)

In [114]:
print(classification_report(y_test,y_predic_test))


              precision    recall  f1-score   support

           0       0.75      0.79      0.77        53
           1       0.79      0.75      0.77        55

    accuracy                           0.77       108
   macro avg       0.77      0.77      0.77       108
weighted avg       0.77      0.77      0.77       108



In [115]:
from sklearn.tree import DecisionTreeClassifier

In [117]:
dtc = DecisionTreeClassifier(random_state=0)

In [119]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [121]:
y_tree_pred_train = dtc.predict(X_train)
y_tree_pred_test =  dtc.predict(X_test)

In [123]:
print(classification_report(y_train,y_tree_pred_train))
print(classification_report(y_test,y_tree_pred_test))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00       215
           1       1.00      1.00      1.00       213

    accuracy                           1.00       428
   macro avg       1.00      1.00      1.00       428
weighted avg       1.00      1.00      1.00       428

              precision    recall  f1-score   support

           0       0.64      0.66      0.65        53
           1       0.66      0.64      0.65        55

    accuracy                           0.65       108
   macro avg       0.65      0.65      0.65       108
weighted avg       0.65      0.65      0.65       108

